import type { Post } from "./types/post-type";

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    title: 'Next.js 14 App Router 완전 정복하기',
    author: '김개발',
    category: '프론트엔드',
    postDate: '2024-11-14',
    content: 'Next.js 14의 새로운 App Router에 대해 자세히 알아보겠습니다.',
  },
  {
    id: '2',
    title: 'TypeScript 타입 시스템 이해하기',
    author: '박타입',
    category: '언어',
    postDate: '2024-11-13',
    content: 'TypeScript의 강력한 타입 시스템을 마스터해봅시다.',
  },
  {
    id: '3',
    title: 'React Query vs SWR 비교 분석',
    author: '이쿼리',
    category: '프론트엔드',
    postDate: '2024-11-12',
    content: '서버 상태 관리 라이브러리들을 비교 분석해보겠습니다.',
  },
  {
    id: '4',
    title: 'Zustand로 상태관리 마스터하기',
    author: '최상태',
    category: '상태관리',
    postDate: '2024-11-11',
    content: 'Zustand를 사용한 효율적인 상태 관리 방법을 알아봅시다.',
  },
  {
    id: '5',
    title: 'Tailwind CSS 디자인 시스템 구축',
    author: '김스타일',
    category: 'CSS',
    postDate: '2024-11-10',
    content: 'Tailwind CSS로 확장 가능한 디자인 시스템을 만들어봅시다.',
  },
  {
    id: '6',
    title: 'Node.js Express 서버 최적화',
    author: '서버러',
    category: '백엔드',
    postDate: '2024-11-09',
    content: 'Express 서버의 성능을 최적화하는 방법들을 알아봅시다.',
  },
  {
    id: '7',
    title: 'PostgreSQL 성능 튜닝 가이드',
    author: 'DB관리자',
    category: '데이터베이스',
    postDate: '2024-11-08',
    content: 'PostgreSQL 데이터베이스 성능을 향상시키는 방법들을 살펴봅시다.',
  },
  {
    id: '8',
    title: 'Docker 컨테이너 배포 전략',
    author: '데브옵스',
    category: 'DevOps',
    postDate: '2024-11-07',
    content: 'Docker를 활용한 효율적인 배포 전략을 알아봅시다.',
  },
  {
    id: '9',
    title: 'AWS Lambda 서버리스 아키텍처',
    author: '클라우드',
    category: '클라우드',
    postDate: '2024-11-06',
    content: 'AWS Lambda를 활용한 서버리스 아키텍처 설계 방법',
  },
  {
    id: '10',
    title: 'GraphQL API 설계 패턴',
    author: '그래프',
    category: 'API',
    postDate: '2024-11-05',
    content: 'GraphQL을 사용한 효율적인 API 설계 패턴들',
  },
  {
    id: '11',
    title: 'Redis 캐싱 전략 완벽 가이드',
    author: '캐시마스터',
    category: '데이터베이스',
    postDate: '2024-11-04',
    content: 'Redis를 활용한 다양한 캐싱 전략들을 알아봅시다.',
  },
  {
    id: '12',
    title: 'Jest 단위 테스트 베스트 프랙티스',
    author: '테스터',
    category: '테스팅',
    postDate: '2024-11-03',
    content: 'Jest를 사용한 효과적인 단위 테스트 작성법',
  },
];