import type { Post } from "./types/post-type";

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    title: 'Next.js 14 App Router 완전 정복하기',
    author: '김개발',
    category: '프론트엔드',
    postDate: '2024-11-14',
    content: 'Next.js 14의 새로운 App Router에 대해 자세히 알아보겠습니다.',
  },
  {
    id: '2',
    title: 'TypeScript 타입 시스템 이해하기',
    author: '박타입',
    category: '언어',
    postDate: '2024-11-13',
    content: 'TypeScript의 강력한 타입 시스템을 마스터해봅시다.',
  },
  {
    id: '3',
    title: 'React Query vs SWR 비교 분석',
    author: '이쿼리',
    category: '프론트엔드',
    postDate: '2024-11-12',
    content: '서버 상태 관리 라이브러리들을 비교 분석해보겠습니다.',
  },
  {
    id: '4',
    title: 'Zustand로 상태관리 마스터하기',
    author: '최상태',
    category: '상태관리',
    postDate: '2024-11-11',
    content: 'Zustand를 사용한 효율적인 상태 관리 방법을 알아봅시다.',
  },
  {
    id: '5',
    title: 'Tailwind CSS 디자인 시스템 구축',
    author: '김스타일',
    category: 'CSS',
    postDate: '2024-11-10',
    content: 'Tailwind CSS로 확장 가능한 디자인 시스템을 만들어봅시다.',
  },
  {
    id: '6',
    title: 'Node.js Express 서버 최적화',
    author: '서버러',
    category: '백엔드',
    postDate: '2024-11-09',
    content: 'Express 서버의 성능을 최적화하는 방법들을 알아봅시다.',
  },
  {
    id: '7',
    title: 'PostgreSQL 성능 튜닝 가이드',
    author: 'DB관리자',
    category: '데이터베이스',
    postDate: '2024-11-08',
    content: 'PostgreSQL 데이터베이스 성능을 향상시키는 방법들을 살펴봅시다.',
  },
  {
    id: '8',
    title: 'Docker 컨테이너 배포 전략',
    author: '데브옵스',
    category: 'DevOps',
    postDate: '2024-11-07',
    content: 'Docker를 활용한 효율적인 배포 전략을 알아봅시다.',
  },
  {
    id: '9',
    title: 'AWS Lambda 서버리스 아키텍처',
    author: '클라우드',
    category: '클라우드',
    postDate: '2024-11-06',
    content: 'AWS Lambda를 활용한 서버리스 아키텍처 설계 방법',
  },
  {
    id: '10',
    title: 'GraphQL API 설계 패턴',
    author: '그래프',
    category: 'API',
    postDate: '2024-11-05',
    content: 'GraphQL을 사용한 효율적인 API 설계 패턴들',
  },
  {
    id: '11',
    title: 'Redis 캐싱 전략 완벽 가이드',
    author: '캐시마스터',
    category: '데이터베이스',
    postDate: '2024-11-04',
    content: 'Redis를 활용한 다양한 캐싱 전략들을 알아봅시다.',
  },
  {
    id: '12',
    title: 'Jest 단위 테스트 베스트 프랙티스',
    author: '테스터',
    category: '테스팅',
    postDate: '2024-11-03',
    content: 'Jest를 사용한 효과적인 단위 테스트 작성법',
  },
  {
    id: '13',
    title: 'CI/CD 파이프라인 구축하기',
    author: '배포마스터',
    category: 'DevOps',
    postDate: '2024-11-02',
    content: 'CI/CD 파이프라인을 구축하는 방법에 대해 알아봅시다.',
  },
  {
    id: '14',
    title: 'React 19 Suspense와 렌더링 최적화',
    author: '김개발',
    category: '프론트엔드',
    postDate: '2024-11-01',
    content: 'React 19의 새로운 기능과 Suspense를 활용한 렌더링 최적화',
  },
  {
    id: '15',
    title: 'WebSockets 실시간 채팅 구현',
    author: '서버러',
    category: '백엔드',
    postDate: '2024-10-31',
    content: 'Node.js와 WebSockets을 이용한 실시간 채팅 서버 만들기',
  },
  {
    id: '16',
    title: 'useEffect 완벽 가이드',
    author: '박타입',
    category: '프론트엔드',
    postDate: '2024-10-30',
    content: 'React의 useEffect 훅의 모든 것을 파헤쳐봅니다.',
  },
  {
    id: '17',
    title: 'Kubernetes 기초와 배포 실습',
    author: '데브옵스',
    category: 'DevOps',
    postDate: '2024-10-29',
    content: 'Kubernetes의 기본 개념과 실제 배포 실습을 다룹니다.',
  },
  {
    id: '18',
    title: 'CSS Grid 레이아웃 마스터',
    author: '김스타일',
    category: 'CSS',
    postDate: '2024-10-28',
    content: 'CSS Grid를 활용한 반응형 웹 레이아웃 설계',
  },
  {
    id: '19',
    title: 'gRPC와 Protobuf 소개',
    author: '그래프',
    category: 'API',
    postDate: '2024-10-27',
    content: 'gRPC를 이용한 고성능 마이크로서비스 통신',
  },
  {
    id: '20',
    title: 'Python Django 웹 프레임워크',
    author: '장고맨',
    category: '백엔드',
    postDate: '2024-10-26',
    content: 'Django를 활용한 빠르고 안정적인 웹 개발',
  },
  {
    id: '21',
    title: 'Rust 언어 입문하기',
    author: '박타입',
    category: '언어',
    postDate: '2024-10-25',
    content: '안전하고 빠른 시스템 프로그래밍 언어, Rust',
  },
  {
    id: '22',
    title: 'MySQL 인덱싱 전략',
    author: 'DB관리자',
    category: '데이터베이스',
    postDate: '2024-10-24',
    content: 'MySQL 성능 향상을 위한 올바른 인덱스 설계',
  },
  {
    id: '23',
    title: 'Storybook을 활용한 컴포넌트 주도 개발(CDD)',
    author: '김개발',
    category: '프론트엔드',
    postDate: '2024-10-23',
    content: 'Storybook으로 UI 컴포넌트를 효율적으로 개발하고 테스트합니다.',
  },
  {
    id: '24',
    title: 'React Native vs Flutter 비교',
    author: '모바일개발',
    category: '모바일',
    postDate: '2024-10-22',
    content: '크로스플랫폼 모바일 앱 개발 프레임워크 비교',
  },
  {
    id: '25',
    title: 'GitHub Actions 자동화',
    author: '데브옵스',
    category: 'DevOps',
    postDate: '2024-10-21',
    content: 'GitHub Actions로 CI/CD 파이프라인 자동화하기',
  },
  {
    id: '26',
    title: 'Kafka 메시지 큐 시스템',
    author: '서버러',
    category: '백엔드',
    postDate: '2024-10-20',
    content: '대용량 데이터 처리를 위한 Kafka 메시지 큐',
  },
  {
    id: '27',
    title: '웹 보안 기초: XSS와 CSRF',
    author: '보안전문가',
    category: '보안',
    postDate: '2024-10-19',
    content: '웹 애플리케이션의 일반적인 보안 취약점 알아보기',
  },
  {
    id: '28',
    title: 'TensorFlow와 Keras를 이용한 딥러닝',
    author: '인공지능',
    category: 'AI',
    postDate: '2024-10-18',
    content: 'TensorFlow 2.0과 Keras로 딥러닝 모델 구축하기',
  },
  {
    id: '29',
    title: 'OAuth 2.0 인증 구현하기',
    author: '보안전문가',
    category: '보안',
    postDate: '2024-10-17',
    content: 'OAuth 2.0 프로토콜의 이해와 실제 구현 방법',
  },
  {
    id: '30',
    title: 'Svelte와 SvelteKit 소개',
    author: '김개발',
    category: '프론트엔드',
    postDate: '2024-10-16',
    content: '새로운 웹 프레임워크 Svelte의 특징과 사용법',
  },
  {
    id: '31',
    title: 'MongoDB NoSQL 데이터 모델링',
    author: 'DB관리자',
    category: '데이터베이스',
    postDate: '2024-10-15',
    content: 'MongoDB를 위한 유연하고 확장 가능한 데이터 모델링',
  },
  {
    id: '32',
    title: 'Go 언어 동시성 프로그래밍',
    author: '박타입',
    category: '언어',
    postDate: '2024-10-14',
    content: 'Go 언어의 고루틴과 채널을 활용한 동시성 처리',
  },
  {
    id: '33',
    title: 'Cypress E2E 테스트 자동화',
    author: '테스터',
    category: '테스팅',
    postDate: '2024-10-13',
    content: 'Cypress를 이용한 End-to-End 테스트 환경 구축',
  },
  {
    id: '34',
    title: 'Recoil 상태 관리 라이브러리',
    author: '최상태',
    category: '상태관리',
    postDate: '2024-10-12',
    content: 'React를 위한 또 다른 상태 관리 솔루션, Recoil',
  },
  {
    id: '35',
    title: 'AWS S3와 CloudFront로 정적 웹 배포',
    author: '클라우드',
    category: '클라우드',
    postDate: '2024-10-11',
    content: 'S3와 CloudFront를 이용한 빠르고 저렴한 정적 웹사이트 배포',
  },
  {
    id: '36',
    title: 'PyTorch 딥러닝 프레임워크',
    author: '인공지능',
    category: 'AI',
    postDate: '2024-10-10',
    content: 'PyTorch를 활용한 유연한 딥러닝 모델 개발',
  },
  {
    id: '37',
    title: 'NestJS 백엔드 프레임워크',
    author: '서버러',
    category: '백엔드',
    postDate: '2024-10-09',
    content: 'TypeScript 기반의 Node.js 백엔드 프레임워크 NestJS',
  },
  {
    id: '38',
    title: 'SwiftUI 아이폰 앱 개발',
    author: '모바일개발',
    category: '모바일',
    postDate: '2024-10-08',
    content: 'SwiftUI를 사용한 선언적 iOS 앱 개발',
  },
  {
    id: '39',
    title: 'styled-components vs Emotion',
    author: '김스타일',
    category: 'CSS',
    postDate: '2024-10-07',
    content: 'CSS-in-JS 라이브러리인 styled-components와 Emotion 비교',
  },
  {
    id: '40',
    title: 'JWT 토큰 기반 인증',
    author: '보안전문가',
    category: '보안',
    postDate: '2024-10-06',
    content: 'JSON Web Token(JWT)을 활용한 안전한 인증 시스템 구현',
  },
  {
    id: '41',
    title: 'Elasticsearch 검색 엔진 구축',
    author: 'DB관리자',
    category: '데이터베이스',
    postDate: '2024-10-05',
    content: 'Elasticsearch를 이용한 강력한 전문 검색 엔진 구축하기',
  },
  {
    id: '42',
    title: 'Vite 프론트엔드 빌드 툴',
    author: '김개발',
    category: '프론트엔드',
    postDate: '2024-10-04',
    content: '빠른 속도를 자랑하는 차세대 프론트엔드 빌드 툴 Vite',
  },
  {
    id: '43',
    title: 'Kotlin 안드로이드 앱 개발',
    author: '모바일개발',
    category: '모바일',
    postDate: '2024-10-03',
    content: 'Kotlin을 활용한 현대적인 안드로이드 앱 개발',
  },
];
